### PR TITLE
Adding links to AppServiceTriggerDetails

### PR DESCRIPTION
**Pull request by ptorr-msft**
Current topic doesn't make it easy to figure out the server side of the equation.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ptorr-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@mijacobs, can you review this PR? Thanks.

**Comment by mijacobs** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
