### PR TITLE
Update virtualkeymodifiers.md

### PR DESCRIPTION
**Pull request by DJm00n**
To be on par with Windows.System.VirtualKey key descriptions.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@hickeys

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft can you please take a look?

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft any updates?

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Pull request merged**
