### PR TITLE
Update imemorybufferreference.md

### PR DESCRIPTION
**Pull request by jaigak**
Adds link for IMemoryBufferByteAccess docs from previous versions.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
If the update is approved, before merging, we'll need to remove the locale from the links, and preferably change the links to relative links.

**Review by hickeys — CHANGES_REQUESTED** [review]
Please remove `/en-us` from the added links and this change is good to go!

**Comment by ktoliver** [comment]
@Jaiganeshkumaran Please remove `/en-us` from the added links and then we'll merge.

(I typically can make this change and then merge, but the **Edit file** option is inactive for me in this pull request.)

Thanks.

**Comment by jaigak** [comment]
@ktoliver It seems like the branch for this pull request was deleted so I've opened a new one: #2060.

**Pull request closed without merging**
