### PR TITLE
Mention important gotcha related to RequestedUri updates

### PR DESCRIPTION
**Pull request by Diego-Perez-Botero**
Adding important information around OS limitations in Windows 10 1709.

### CODE REVIEW

**Comment by mikematteson** [comment]
@mcleblanc : PR **passed** review checklist. Note that the contribution includes an unmapped link in square brackets; perhaps provide target URL or remove the brackets. Please evaluate the proposed changes further. Thanks!

**Comment by Diego-Perez-Botero** [comment]
I've fixed the unmapped link issue :)

**Comment by mikematteson** [comment]
@Diego-Perez-Botero : Thanks for the link fix!

@stevewhims : Assigning to you now, after mistaking @mcleblanc as the CX owner of this ref page. PR **passed** review checklist, so please evaluate the proposed changes further and merge if appropriate. Thanks!

**Comment by stevewhims** [comment]
I removed the quote marks, because leaving them there seems to be implying that the mode isn't really random access.

**Review by stevewhims — APPROVED** [review]
LGTM

**Pull request merged**
