### PR TITLE
Update textbox_selectionflyout.md

### PR DESCRIPTION
**Pull request by asklar**

### CODE REVIEW

**Comment by Court72** [comment]
@Karl-Bridge-Microsoft 

Are you the correct person to review the proposed changes? If not, could you assign a reviewer who might be?

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Karl-Bridge-Microsoft** [comment]
@asklar - please review. I revised entire topic and added "touchpad" to your note about mouse input.

**Comment by asklar** [comment]
thanks @Karl-Bridge-Microsoft !  could you please also update the equivalent winui 3 property? (

**Comment by Karl-Bridge-Microsoft** [comment]
@asklar - Will do!

**Pull request merged**
