### PR TITLE
Update iuritostreamresolver.md

### PR DESCRIPTION
**Pull request by MancunianBandit**
Testing autoassignment/labeling. Added whitespace and updated link to sample (fwlink -> full url).

### CODE REVIEW

**Comment by PRMerger18** [comment]
@MancunianBandit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@stevewhims @Karl-Bridge-Microsoft @GrantMeStrength  - Is this user known to you? He has submitted about a dozen "test" and "testing PRMerger" PRs to the repo since January: https://github.com/MicrosoftDocs/winrt-api/commits?author=MancunianBandit

Open "test" PRs in the public repo queue that require manual management and review:
https://github.com/MicrosoftDocs/winrt-api/pull/1541
https://github.com/MicrosoftDocs/winrt-api/pull/1539
https://github.com/MicrosoftDocs/winrt-api/pull/1537
https://github.com/MicrosoftDocs/winrt-api/pull/1535
https://github.com/MicrosoftDocs/winrt-api/pull/1533
https://github.com/MicrosoftDocs/winrt-api/pull/1531

Thanks.

**Comment by stevewhims** [comment]
The description of this one does start out characterizing it as a "test". But then it conflates that with a genuine (and beneficial) change to a url. So I'll take this change. Btw, if @MancunianBandit is a Microsoft employee, and knows who I am (:)), then do you mind pinging me a brief email saying hi, and then we'll know who you are. Thank you! :) ~Steve

**Comment by stevewhims** [comment]
@ktoliver, I'll send a mail to my team enquiring about the user. Thanks! ~Steve

**Pull request merged**
