### PR TITLE
Update processlauncher_runtocompletionasync_1909636529.md

### PR DESCRIPTION
**Pull request by paulmon**
Add information about whitelisting executables

### CODE REVIEW

**Comment by mikematteson** [comment]
Hi @paulmon: Thanks for your contribution. Going forward, CX asks that Microsoft contributors use VSTS to submit documentation changes. Future contributions via GitHub will be closed with a request to resubmit them via VSTS. More information is at http://aka.ms/windowsauthoring (see **UWP instructions** > **UWP/WinRT API content**). Thanks!

**Comment by mikematteson** [comment]
@TylerMSFT: PR **passed** checklist review. Please evaluate further and merge if appropriate.

**Comment by TylerMSFT** [comment]
I have a question out to Paul about the update. Will take care of the pull request once that’s taken care of.

**Comment by paulmon** [comment]
@msalehmsft

**Review by mikematteson — APPROVED** [review]
@paulmon: Thanks for the contribution. Much appreciated!

Cc: @TylerMSFT

**Pull request merged**
