### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by reflectronic**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@reflectronic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@alvinashcraft

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by alvinashcraft** [comment]
Hi. I'm in all-day training Mon/Tue/Wed. I'll try to find time during a break or before/after training.

**Review by alvinashcraft — APPROVED** [review]

**Comment by alvinashcraft** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@alvinashcraft: I'm sorry - only the author of this article, @mikben, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by alvinashcraft** [comment]
Looks like the wrong account is linked. Alias should be @MatchaMatch not @mikben.

**Pull request merged**
