### PR TITLE
Update coreapplication.md

### PR DESCRIPTION
**Pull request by Gavin-Williams**
Added C# code snippets.
Changed C++ code section language to C++/CX.
Slightly extended remarks.
Moved Windows Phone 8 remark regarding native API to main remarks section.
Removed Windows Phone 8 section.

### CODE REVIEW

**Comment by Gavin-Williams** [comment]
Note that I needed to slightly amend the pull request. I wasn't sure how to do that so I closed and opened a new pull request, thinking it would submit everything at once, but instead it reopened the first and opened a second one, which looks wonky. Apologies.

**Comment by garycentric** [comment]
@knicholasa : The PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

**Review by aeloros — COMMENTED** [review]
The below text feels redundant.  If the existing text requires clarity, maybe it should be reworded instead.
"Put another way, any thread that you spin off from the ASTA must be in an MTA."

What is the intent behind the DirectX comment?  What drove you to put it here?

**Comment by Gavin-Williams** [comment]
I agree that the wording is poor regarding "Put another way …" I didn't want to change what was there, but wanted to include a small detail about apartments which is a poorly understood concept at my level. I can look at it a bit closer and reword it.

Regarding the DirectX comment, I merely wanted to clarify what would be the appropriate annotation for that scenario. Probably again coming from a perspective of not really understanding the significance of apartments. I see it as a detail that can be included here to help developers get this stuff right. It's an annotation that in some cases will be used just once in a project and never thought of again. It may be more appropriate to keep MTA info elsewhere, I have no experience with documentation so I don't know how free we are to discuss details of the code.

Edit: Perhaps I should steer clear of details that I'm not 100% sure of. I think I'm correct with the [MTAThread] being the appropriate annotation for DX apps. But that's probably just a consequence of it being appropriate for a range of applications.

**Comment by knicholasa** [comment]
@Gavin-Williams  Did you still want to make a change here or did you find the original wording sufficient after rereading it? If you still want to make a change, can you restate what it was that confused you about the original wording so we can tweak this PR appropriately? Thanks!

**Comment by Gavin-Williams** [comment]
Yes I will reword this and submit something soon. Thanks.

**Comment by Gavin-Williams** [comment]
So I agree that the original wording is fine, I've added a link to MTAThreadAttribute page for further reading. And the main change then becomes what I originally intended, the C# snippet.

I'm working on my git and GitHub skills, so what I've done is - I made a commit directly to my branch, GitHub has seemed to pick it up automatically ( commit 7c1502f ) and added the changes to this pull request. So that should be a bit tidier than my first attempt where I think I closed the pull request and made another just to make a change. And .. I just noticed straight under this edit box .. 'Add more commits by pushing to the docs branch on <my/rep>'

PS. Sry for too much handling for such a minor change. I will get the hang of this and next pull request will be closer to being 'ready to publish'.

**Comment by aeloros** [comment]
> So I agree that the original wording is fine, I've added a link to MTAThreadAttribute page for further reading. And the main change then becomes what I originally intended, the C# snippet.
> 
> I'm working on my git and GitHub skills, so what I've done is - I made a commit directly to my branch, GitHub has seemed to pick it up automatically ( commit [7c1502f](https://github.com/MicrosoftDocs/winrt-api/commit/7c1502f897bd044c07371cb0a1e4ba7b2a156fa2) ) and added the changes to this pull request. So that should be a bit tidier than my first attempt where I think I closed the pull request and made another just to make a change. And .. I just noticed straight under this edit box .. 'Add more commits by pushing to the docs branch on <my/rep>'
> 
> PS. Sry for too much handling for such a minor change. I will get the hang of this and next pull request will be closer to being 'ready to publish'.

Awesome!  Things look much better.  Could we maybe also add this to the see also references?

https://docs.microsoft.com/en-us/previous-versions/ms809971(v=msdn.10)

@knicholasa could you verify that my link is the most up to date version of that document?  The 'previous-versions' part concerns me.

Thanks
--Scott

**Comment by knicholasa** [comment]
@aeloros How about linking to this article instead? https://docs.microsoft.com/en-us/windows/desktop/com/processes--threads--and-apartments

**Comment by aeloros** [comment]
> @aeloros How about linking to this article instead? https://docs.microsoft.com/en-us/windows/desktop/com/processes--threads--and-apartments

Awesome, let's use that instead.

Thanks
--Scott

**Review by aeloros — APPROVED** [review]

**Review by knicholasa — APPROVED** [review]

**Comment by knicholasa** [comment]
@Gavin-Williams Thanks for your contribution! Completing the PR.

**Pull request merged**
