### PR TITLE
Added link to sample code: ListViewBase.ScrollIntoView

### PR DESCRIPTION
**Pull request by anawishnoff**
Implementing a simple fix that solves #1382.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@anawishnoff : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jwmsft — CHANGES_REQUESTED** [review]
@anawishnoff, Docs reference pages can only have a comma separated list for the see-also section. The doc build will format it as a bulleted list. Anything else in the see-also section will not render correctly. please revert that section to the comma separated list.

**Comment by anawishnoff** [comment]
@jwmsft Just fixed, thanks!

**Comment by PRMerger20** [comment]
@anawishnoff : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jwmsft — APPROVED** [review]

**Pull request merged**
