### PR TITLE
Update Binding.Mode documentation

### PR DESCRIPTION
**Pull request by Felix-Dev**
* Add more information on the default value: OneWay for {Binding}, OneTime for {x:Bind}
* Add mention of the x:DefaultBindMode attribute to change the default binding mode for {x:Bind}
* Add C++/WinRT mention alongside C++/CX mention.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@Felix-Dev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Felix-Dev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jwmsft** [comment]
@Felix-Dev, this reference doc is specific to the Binding class, so the information about x:Bind doesn't belong here. The [BindingMode](https://docs.microsoft.com/uwp/api/windows.ui.xaml.data.bindingmode) enumeration would be a good place for this information, though.

**Comment by Felix-Dev** [comment]
@jwmsft Sorry for the late reply.

Your comment makes sense, this is the wrong place to include such info. I am not sure the BindingMode enumeration doc is the right place either - it should focus on describing the different binding modes and how they differ from each other. That documentation, in my opinion, shouldn't have knowledge about the default binding mode for either `Binding` or `{x:Bind}`.

If you still think it would be a good place though, I could add a comment to the `OneTime` and `OneWay` mode descriptions, i.e. for `OneTime`: "Updates the target property when the binding is created. This is the default binding mode for {x:Bind}."

Reading through the [x:Bind](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension) documentation, we put some good emphasis on the differences between `{x:Bind}` and `Binding` in regards to their BindingMode. This is probably sufficient.

**Comment by jwmsft** [comment]
Thanks, @Felix-Dev. I agree, we typically try to not put information about default values in the enumeration docs. I'll close this PR, but look out for other feedback to see if we need to further clarify this.

**Pull request closed without merging**
