### PR TITLE
Fix DirectX11 example in iframeworkview.md

### PR DESCRIPTION
**Pull request by mcleary**
Need to use `make` method to instantiate `App` otherwise you get `error C2259: 'App': cannot instantiate abstract class`

### CODE REVIEW

**Comment by PRMerger9** [comment]
@mcleary : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@mcleary : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @stevewhims - Are you able to verify the proposed update and indicate whether the PR can be merged? Thanks.

**Comment by PRMerger9** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
