### PR TITLE
Host backdrop brush can be not translucent

### PR DESCRIPTION
**Pull request by MolusMS**
The host backdrop brush transparency can be controlled through the Settings UI or through power policies. Added this information to the remarks section.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@MolusMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@jwmsft Could you take a look at a proposed update to your article? Thanks.

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
