### PR TITLE
Update retailinfo.md

### PR DESCRIPTION
**Pull request by ZodmanPerth**
The label for the link that should not be used was the same as the label for the link that should be used.  This change prevents confusion.

### CODE REVIEW

**Comment by Kellylorenebaker** [comment]
@hickeys : PR **passed** the acceptance checklist. Please evaluate further and approve/merge if appropriate. Thanks!

**Comment by PRMerger8** [comment]
@ZodmanPerth : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ZodmanPerth** [comment]
Wow, that took a while.  Did it fall through the cracks?

**Review by hickeys — APPROVED** [review]

**Comment by PRMerger18** [comment]
@hickeys : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
