### PR TITLE
Update mobilebroadbandsarmanager_starttransmissionstatemonitoring_144…

### PR DESCRIPTION
**Pull request by charliearcuri**
…5651691.md

transition should be transmission

### CODE REVIEW

**Comment by mattwojo** [comment]
@duncanmacmichael - Are you the correct person to review and merge?

**Comment by duncanmacmichael** [comment]
Sorry, but I'm not. @GrantMeStrength would be able to help, though. Thanks!

**Comment by mikematteson** [comment]
@mattwojo @duncanmacmichael  Typo fix, so editorial can merge.

**Review by mikematteson — APPROVED** [review]
@charliearcuri Thanks for your help with this one too!

CC: @mcleblanc

**Pull request merged**
