### PR TITLE
Pointer to AccountSettingsPaneInterop class

### PR DESCRIPTION
**Pull request by angelazhangmsft**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@angelazhangmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by angelazhangmsft** [comment]
Addresses https://github.com/MicrosoftDocs/winrt-api/issues/1709

**Comment by jborsecnik** [comment]
@Karl-Bridge-Microsoft, when you review this, please check the links. Or, if necessary, we can bring this over to the private repo for validation. Thanks.

**Comment by Karl-Bridge-Microsoft** [comment]
@stevewhims - i think you've been working on this topic with Angela, so I assigned the PR to you.

**Comment by PRMerger19** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevewhims** [comment]
Since there are feature team folks added (presumably for technical review), I'll hold off from merging. I did a minor edit pass for style.

Please let me know, or leave #sign-off, when this is ready for merging.

Thanks
-Steve

**Comment by PRMerger7** [comment]
@stevewhims: I'm sorry - only the author of this article, @Karl-Bridge-Microsoft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
