### PR TITLE
Clarify documenation for MediaFrameReference intrinsics and extrinsics

### PR DESCRIPTION
**Pull request by dfields-msft**
Added details to clarify the semantics of the APIs for handling camera intrinsics and extrinsics for a MediaFrameReference.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by drewbatgit — APPROVED** [review]

**Comment by ktoliver** [comment]
@dfields-msft Hi, is your PR ready to be merged? It's been approved by a content owner but it's still in GitHub draft mode. Could you either set it to ready for review or close the PR and do the work in the private repository? Thanks!

**Comment by dfields-msft** [comment]
@ktoliver I didn't expect publishing a draft PR to trigger any process; I'm still consulting with the feature team to confirm these changes, and a PR was a simple way to show what changes were needed. Once I get confirmation from the feature team, I'll publish the PR for real.

**Comment by ktoliver** [comment]
@dfields-msft Understood. And I just recalled that this is one of the few Microsoft repos that don't have a public/private divide--it's all public.

**Comment by PRMerger18** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@drewbatgit - You approved this PR earlier, when it was still in progress. Do the final updates look good to merge? Thanks.

**Pull request merged**
