### PR TITLE
Update window_activate_1797342875.md

### LINKED ISSUE #2091: "App will be terminated after 15 seconds if Windows.Activate is not called" doesn't seem to apply to WinUI
> If an app does not call Activate on the Current window, and the app is not visible on screen, **then the app will be terminated after 15 seconds**

A few minutes have passed, my app is still alive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fce2b875-b1c6-367a-0de3-4385915d65a7
* Version Independent ID: 4d6fd459-3b7e-7d84-4b82-dc81c9f5e912
* Content: [Window.Activate Method (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.window.activate?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/Window.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

### PR DESCRIPTION
**Pull request by jaigak**
Fixes #2091.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by mohsen12852** [comment]
> اصلاحات [# 2091](https://github.com/MicrosoftDocs/winrt-api/issues/2091).

https://github.com/MicrosoftDocs/winrt-api/pull/2124#issue-1065728362

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
#sign-off

**Pull request merged**
