### PR TITLE
Update navigationview_displaymode.md

### PR DESCRIPTION
**Pull request by Trannosaur**
DisplayMode reflects that mode the NavView is currently in based on the CompactModeThresholdWidth/ExpandedModeThresholdWidth values. It is not intended to be settable (and indeed can't be).

### CODE REVIEW

**Comment by Trannosaur** [comment]
someone else complete this when it's done please..., I have no idea how this works, and thought it'd just be automatic

**Comment by Trannosaur** [comment]
I say tis because I haven't received any email at my private or work email in response to this so I'mn gonna assume I'm not gonna notice when it's approved

**Comment by mikematteson** [comment]
Hi @Trannosaur ; Yes, there's a review/approval process. You should see notifications as the PR moves through it. Thanks for contributing!

**Comment by mikematteson** [comment]
@jwmsft : PR **passed** review checklist. Please evaluate the proposed changes further. Thanks!

**Review by jwmsft — APPROVED** [review]

**Pull request merged**
