### PR TITLE
Update radio_fromidasync_1322863552.md

### PR DESCRIPTION
**Pull request by HappyDawgie**

### CODE REVIEW

**Comment by HappyDawgie** [comment]
Still getting the hang of this screen. I will comment and leave this open - it appears to be better than closing it.

**Comment by HappyDawgie** [comment]
But it seems to prefer being closed...

**Comment by mikematteson** [comment]
@laurenhughes : PR **passed** review checklist. Please evaluate the proposed changes further. Thanks!
@HappyDawgie : Thanks for your contribution. From your comments, it sounds like you have had some trouble with the GitHub UI for this PR; is that true? Did you intend to close the PR or do you want us to consider it for merging?

**Comment by HappyDawgie** [comment]
I did not understand the GitHub use of Close ... Apparently it means terminate when on Windows it means complete or submit. So I reopened the issue and that seems to do the trick.


Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by laurenhughes** [comment]
@HappyDawgie, this is currently being investigated by the dev team. I'll report any findings back here.

Thanks for raising the issue!

**Comment by HappyDawgie** [comment]
Thank you !

**Review by FrankGorgenyi — APPROVED** [review]
These edits are correct.

**Review by laurenhughes — APPROVED** [review]

**Pull request merged**
