### PR TITLE
Document auto-unregistration of BackgroundTransferCompletionGroup tasks

### PR DESCRIPTION
**Pull request by ghost**
Document auto-unregistration of BackgroundTransferCompletionGroup tasks in support of Windows-universal-samples issue [1054](https://github.com/Microsoft/Windows-universal-samples/issues/1054) to make it clear that if developers use BackgroundTransferCompletionGroup.Trigger to build and register their background tasks, no explicit unregistration code is needed.

### CODE REVIEW

**Comment by garycentric** [comment]
@stevewhims  : The PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

**Review by Diego-Perez-Botero — APPROVED** [review]
LGTM

**Review by DavidGoll — APPROVED** [review]
:shipit:

**Review by stevewhims — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
