### PR TITLE
fix code and text typo

### PR DESCRIPTION
**Pull request by ahmed605**
`dispatcher` must be `Dispatcher`
`CoreDispatcher.RunAsync` must be `Dispatcher.RunAsync`

### CODE REVIEW

**Comment by PRMerger16** [comment]
@ahmed605 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ahmed605 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@GrantMeStrength - It looks like you're the listed author for the article. Could you review the pull request? Thanks.

image

**Comment by ktoliver** [comment]
@jwmsft Hi, could you review the proposed changes? Thanks.

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
#sign-off

**Pull request merged**
