### PR TITLE
Document interpretation of axis-angle quantities

### PR DESCRIPTION
**Pull request by dfields-msft**
The SpatialLocation API provides angular velocity and acceleration as axis-angle values, but the documentation does not explain how to interpret these values. These changes add details to explain how the values should be interpreted. It also clarifies some quirks in the implementation which are essential to understand in order to use the APIs.

### CODE REVIEW

**Comment by ktoliver** [comment]
@hickeys Could you review this pull request? 

Thank you

**Comment by dfields-msft** [comment]
@thetuvix FYI.

**Comment by PRMerger14** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@dfields-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by drewbatgit — APPROVED** [review]

**Pull request merged**
