### PR TITLE
Sample code is in a HTML not in a javascript

### PR DESCRIPTION
**Pull request by aberus**

### CODE REVIEW

**Comment by garycentric** [comment]
PRRT: review required

**Comment by garycentric** [comment]
@mcleanbyron  : The PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

**Review by mcleanbyron — COMMENTED** [review]
Thanks for submitting your changes to our docs. In this case I think you could argue for either HTML or JavaScript tagging, but I'm fine with going with HTML.

**Review by mcleanbyron — APPROVED** [review]

**Comment by aberus** [comment]
I agree it could be either HTML or JavaScript. But syntax highlighting is not properly shown on the sample.

**Pull request merged**
