### PR TITLE
Update mobilebroadbandsarmanager_stoptransmissionstatemonitoring_1111…

### PR DESCRIPTION
**Pull request by charliearcuri**
…799607.md

transition should be transmission

### CODE REVIEW

**Comment by mattwojo** [comment]
@duncanmacmichael

**Comment by duncanmacmichael** [comment]
The edit looks fine to me, but this falls under @GrantMeStrength's team so I can't merge, sorry. He would be better equipped to handle this than I.

**Review by mikematteson — APPROVED** [review]
@charliearcuri Thanks for taking time to fix this for us. Much appreciated!

CC: @mcleblanc

**Comment by mikematteson** [comment]
@mattwojo @duncanmacmichael  This is a typo fix, so editorial can put it through. Thanks!

**Pull request merged**
