### PR TITLE
Updated descriptions of the enums

### PR DESCRIPTION
**Pull request by ptorr-msft**
Provided more information, specifically telling apps they probably don't want to worry about this and that the names are somewhat misleading.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@ptorr-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ptorr-msft** [comment]
How do I add more reviewers? Github UX won't let me.

**Comment by jborsecnik** [comment]
Whom do you want to add? We can try.

**Comment by GitHubber17** [comment]
Hi @ptorr-msft - You can add a Reviewer under the **Reviewers** group box at the top right of the PR:

image

Click the gear icon to open the list of possible Reviewers. Type their name in the text box. When you see their name in the list, click their name and a checkmark should appear next to their name. Click outside the list area. The list will go away and you should see the user listed as a Reviewer.

If the name of the person you're looking for doesn't show up in the text box, then you might try adding them as an Assignee rather than designating them as a Reviewer. You can follow the same process to add a user as an Assignee by using the actions on the **Assignee** group box.

**Comment by ptorr-msft** [comment]
That icon doesn't appear for me on this repo. I can easily add reviewers on other repos, but not this one. It is locked.

**Comment by GitHubber17** [comment]
@ptorr-msft - If you let us know their names or alias, we can try adding them for you.

Also, to add an assignee, you can try using the GitHub comment tag

`#assign:<alias>` like this `#assign:ptorr-msft`

**Comment by ptorr-msft** [comment]
We're working on it on internal mail thread - thanks!

**Review by dianmsft — APPROVED** [review]
Based on the meeting the descriptions look good.

**Pull request merged**
