### PR TITLE
Update mapelement_mapstylesheetentry.md

### PR DESCRIPTION
**Pull request by DavidBuerer**

### CODE REVIEW

**Review by normesta — COMMENTED** [review]
Explanation seems a bit confusing. I believe the developer sets this property to a name that appears in the maps style sheet. If that style is defined in the sheet, then that style is applied to this element. Would it be a bit clearer to use something like that?

**Comment by DavidBuerer** [comment]
Your understanding is correct.  Is your question about the description or the property-value?  Property-value seemed so redundant as to warrant the most bare-bones explanation since the heavy lifting would be in the description.  Is that not a correct assumption?

The description currently has:
Gets or sets the name of the entry of this [MapElement](mapelement.md) in the style sheet. If the style sheet defines a style for that entry, that style is applied to this element. 
That seems pretty in-line with what you have above.  No?

**Comment by normesta** [comment]
The phrase "Gets or sets the name of the entry of this MapElement in the StyleSheet" implies that the style sheet contains an entry solely devoted to this map element. I think its the "entry of this MapElement" that seems confusing. As a suggestion, what about "Gets or sets the name of an entry in the map's style sheet that you'd like to apply to this element". as a description? With the property value being just "The name of an entry in the map's style sheet that you'd like to apply to this element". Then, in the remarks, a brief clarification that if that entry is defined in the stylesheet, then that entry will be applied to this element". Thoughts?

**Review by normesta — APPROVED** [review]
This looks awesome. Thank you David.

**Pull request merged**
