### PR TITLE
Escape broken links for contoso.com

### PR DESCRIPTION
**Pull request by Saisang**
https://dev.azure.com/msft-skilling/Content/_workitems/edit/173987

### CODE REVIEW

**Comment by Court72** [comment]
@stevewhims

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by drewbatgit** [comment]
@Saisang Can you escape the other URLs as well, e.g. info.contoso.com, so that the formatting is the same for all of the URLs?

**Comment by Saisang** [comment]
@drewbatgit I've just updated them.

**Comment by stevewhims** [comment]
Next time, can we please NOT have one writer set as assignee, and a different writer set as reviewer? That's as bad as > 1 person set to either of those lists. Thanks! :) -Steve

UPDATE: Oh, I just realized that Karl did that. I'll ping him. :)

**Comment by stevewhims** [comment]
> @drewbatgit I've just updated them.

I've been asking vendors to leave anything alone that doesn't need to be escaped. I see your point about consistency, but these were already italicized to make them stand out; only the actual uri/url needed escaping. When there are multiple valid stylistic approaches, as here, it would be good if we still had the Style Council. Anyhoo, I don't mind the changes here so I'll take them (even though, as I say, I'm asking for something different in other PRs). :)

-Steve

**Review by stevewhims — APPROVED** [review]

**Comment by drewbatgit** [comment]
@stevewhims - Those are all actual URLs, I believe. There's nothing magic about the www subdomain. But it was out of character for me to nitpick about something so insignificant. I would normally just say fine. But now that I'm trying to defend it, I would say that at some point in the future, urls with different subdomains may turn into build warnings, so maybe it will save us some headaches in the future to fix them now.

**Comment by stevewhims** [comment]
> @stevewhims - Those are all actual URLs, I believe. There's nothing magic about the www subdomain. But it was out of character for me to nitpick about something so insignificant. I would normally just say fine. But now that I'm trying to defend it, I would say that at some point in the future, urls with different subdomains may turn into build warnings, so maybe it will save us some headaches in the future to fix them now.

No, that's good! I don't recognize the word "nitpick", personally. :) Something's either right or wrong (IMHO). But that's why we have Won't Fix as a resolution (for wrong things that are also low-pri). But now I'm interested in looking up exactly what a uri/url's definition is. I would have thought that "contoso.com" was not one, but I'll find out later. :) I was just meaning "things that appear as hyperlinks in the docs". That's an interesting thought about fixing things before they become a problem. But again I could go either way on that concept, too--"in advance" (but we might fix things that'd never need fixing) vs. "just in time" (but we might have to go into the same topic more than once). Interesting.

UPDATE: Well I tried 10 online url parsers. 1 didn't work; 6 said that "contoso.com" is a url; 3 said it isn't. :) I guess it's whatever our docs renderer decides is a url.

**Comment by Court72** [comment]
Thanks for reviewing!

**Pull request merged**
