### PR TITLE
details on directx and hardware vs. software adapters

### PR DESCRIPTION
**Pull request by walrusmcd**
- added details on what happens when you use DirectX opens
- added notes around incorrect behaviour and fixes coming soon

### CODE REVIEW

**Comment by PRMerger9** [comment]
@walrusmcd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ngeisler11 — APPROVED** [review]

**Comment by ktoliver** [comment]
@QuinnRadich Do you want to review this or is it good to go? The update does have a few blocking quality issues. If this is approved, we'll move the commit to the private repository, fix blocking issues, and then merge it. Thanks.

**Comment by QuinnRadich** [comment]
@ktoliver  I was going to make a few edits of my own for quality, but my other issues with it have been resolved. If the PR review team is already planning to look at it, I'll happily hand it over to you do to those clean-ups. Thanks!

**Comment by ktoliver** [comment]
Will do. Thanks @QuinnRadich

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@QuinnRadich I didn't initially notice that this PR is in a repo that doesn't have a private iteration. I've applied our suggested edits. Do these look accurate and OK to you? Thanks.

**Review by QuinnRadich — APPROVED** [review]

**Comment by QuinnRadich** [comment]
Looks good to me, thanks!

**Comment by QuinnRadich** [comment]
#sign-off

**Pull request merged**
