### PR TITLE
Associate CoreCursorType Enum Field Descriptions With Relevant Images

### LINKED ISSUE #1557: Cursor graphics for each CoreCursorType
It would be very helpful to display an image of the cursor for each CoreCursorType value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da15f38-4a63-3242-6714-042d5742dee4
* Version Independent ID: 20fe3e6d-634d-77b0-bf93-d88f10aa7fdc
* Content: [CoreCursorType Enum (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corecursortype#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corecursortype.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corecursortype.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

### PR DESCRIPTION
**Pull request by lukeblevins**
Fixes #1557 
visual

Please let me know if any changes are required.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@duke7553 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@jwmsft - Could you review the proposed updates? Note that the file naming standard for Microsoft Docs doesn't allow underscores in file names. File names can contain only lowercase letters, numbers, and hyphens, and words should be separated by hyphens (arrow-cursor.png).

Thanks.

**Comment by lukeblevins** [comment]
@ktoliver @jwmsft Any update on this?

**Comment by lukeblevins** [comment]
@ktoliver Hello. Did I open this in the wrong repository or something? It's been ignored for over a week now.

**Comment by jwmsft** [comment]
@duke7553, thanks for this contribution. Your PR is assigned to me to review, but I took some time off last week. Please notice that @ktoliver left a comment about the file names needing to be updated before the PR is approved. You can make these updates, or the PR will need to wait until I can schedule some time this week to make them. Thanks

**Comment by lukeblevins** [comment]
@jwmsft Done!

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
@duke7553, thanks! 

#sign-off

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
