### PR TITLE
Added RadialGradientBrush links to LinearGradientBrush and GradientBrush

### PR DESCRIPTION
**Pull request by SavoySchuler**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@SavoySchuler : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @jwmsft Could you review this pull request? Thanks.

**Comment by PRMerger15** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by ktoliver** [comment]
@Karl-Bridge-Microsoft - Are you waiting for input from @chigy and @MikeHillberg or is the update approved for merge?

Thanks.

**Comment by chigy** [comment]
> @Karl-Bridge-Microsoft - Are you waiting for input from @chigy and @MikeHillberg or is the update approved for merge?
> 
> Thanks.

@ktoliver , Karl is not blocked on me, but Mike just got added less than an hour ago. :)

**Comment by Karl-Bridge-Microsoft** [comment]
@ktoliver - waiting for reviews.

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by Karl-Bridge-Microsoft** [comment]
@ktoliver - ready to merge

**Pull request merged**
